[build]
  command   = "npm run build"
  publish   = "dist"

[dev]
  command   = "npm run dev"   # ==> astro dev
  targetPort = 4321           # astro’s default
  framework = "#custom"       # prevent auto-detection

[[plugins]]
  package = "@netlify/plugin-visual-editor"
